# Generated by Django 4.2.16 on 2024-09-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('banID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ban',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('mainBody', models.CharField(max_length=1000)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowingSubreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'FollowingSubreddit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FollowingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'FollowingUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forumID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('mainBody', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Forum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('dateUpload', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('subredditID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Subreddit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('bio', models.CharField(max_length=500, null=True)),
                ('displayName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('profilePicture', models.CharField(max_length=500, null=True)),
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('videoLength', models.IntegerField()),
                ('resolution', models.IntegerField()),
                ('dateUpload', models.DateTimeField()),
            ],
            options={
                'db_table': 'Video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('galleryCount', models.IntegerField()),
            ],
            options={
                'db_table': 'Gallery',
                'managed': False,
            },
        ),
    ]
