# Generated by Django 4.2.16 on 2024-09-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ban_comment_followingsubreddit_followinguser_forum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followingsubreddit',
            options={'managed': True},
        ),
    ]
